image: python:3.14

default:
  before_script:
    - python -m pip install -r requirements_dev.txt

stages:
  - test
  - deploy

pytest:
  stage: test
  script:
    - python -m pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml

pages:
  stage: deploy
  rules:
    # Cannot find option for pages in gitlab, therefore no use of this stage
    # When find usage uncomment only (and remove rules, because cannot be at the same time)
    - when: never 
  script:
    - sphinx-build -b html docs/source public
  pages: true
  #only:
  #  - master
